CFLAGS=-O3 -fopenmp -finline -std=c++11  

MODULES= generateur.cpp experimentations.cpp negative.cpp algoglouton.cpp bskytree.cpp DataGenerator.cpp Gaussian.cpp ValueGenerator.cpp VectorCommon.cpp main.cpp

main: 

	g++ $(CFLAGS) $(MODULES) -o main 


clean:

	rm main